// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBan35AV3pNWlZi4RyFLRjzZNTtQylGTZw',
    appId: '1:836374406934:web:e4c5bfc28c1704d3a05237',
    messagingSenderId: '836374406934',
    projectId: 'astromaagic-b2480',
    authDomain: 'astromaagic-b2480.firebaseapp.com',
    storageBucket: 'astromaagic-b2480.appspot.com',
    measurementId: 'G-77Z1GZ3NTL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC5Ci3VwP8ZJMVropptzfGFRLNjLzxWLbw',
    appId: '1:836374406934:android:4c9cdb7760449809a05237',
    messagingSenderId: '836374406934',
    projectId: 'astromaagic-b2480',
    storageBucket: 'astromaagic-b2480.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDHr1DvTiL82WrcXCur9wKo2L2hNj7_k4w',
    appId: '1:836374406934:ios:70fd9c0cd3e56da3a05237',
    messagingSenderId: '836374406934',
    projectId: 'astromaagic-b2480',
    storageBucket: 'astromaagic-b2480.appspot.com',
    iosBundleId: 'com.mdq.astromaagic',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDHr1DvTiL82WrcXCur9wKo2L2hNj7_k4w',
    appId: '1:836374406934:ios:70fd9c0cd3e56da3a05237',
    messagingSenderId: '836374406934',
    projectId: 'astromaagic-b2480',
    storageBucket: 'astromaagic-b2480.appspot.com',
    iosBundleId: 'com.mdq.astromaagic',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBan35AV3pNWlZi4RyFLRjzZNTtQylGTZw',
    appId: '1:836374406934:web:dd9a420fcca463b6a05237',
    messagingSenderId: '836374406934',
    projectId: 'astromaagic-b2480',
    authDomain: 'astromaagic-b2480.firebaseapp.com',
    storageBucket: 'astromaagic-b2480.appspot.com',
    measurementId: 'G-TTBHEK2KQQ',
  );

}